// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnyyvdxcrhzzuwwkxsek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ueXl2ZHhjcmh6enV3d2t4c2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxODcyMjcsImV4cCI6MjA1Mjc2MzIyN30.-uX5Hz6SVGWc0s-TXK_q0dHTSTV7Rdnl2FqH9YuJr1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);